on:
  pull_request:
    branches:
      - main

env:
  CACHE_VERSION: v1

name: Regress SimDB on Ubuntu
jobs:
  clang-format:
    name: Ensure clang-format was run
    runs-on: ubuntu-24.04

    steps:
      - name: Clone SimDB
        uses: actions/checkout@v4

      - name: Install clang-format
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install -y clang-format-17

      - name: Check formatting
        run: |
          ./.github/actions/clang-format-check.sh

  self-contained-headers:
    name: Ensure headers are self-contained
    runs-on: ubuntu-24.04
    needs: clang-format

    strategy:
      matrix:
        compiler: [gcc,clang]
        build_type: [Debug,Release]

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@v3

      - name: Install compiler
        run: |
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            sudo apt-get install -y g++ 
          else
            sudo apt-get install -y clang
          fi

      - name: Gather headers
        run: |
          mkdir -p build/selfcheck
          find include -name '*.hpp' > build/selfcheck/header_list.txt

      - name: Compiler headers individually
        run: |
          mkdir -p build/selfcheck
          for hdr in $(cat build/selfcheck/header_list.txt); do
            echo "Testing $hdr..."
            # Compile with both C++20, no linking
            ${{ matrix.compiler }} -std=c++20 -Iinclude -c $hdr -o /dev/null
          done

  build_test_job:
    needs: self-contained-headers
    strategy:
      matrix:
        os: [ubuntu-24.04]
        BUILD_TYPE: [Debug,Release]
        COMPILER: [gcc,clang]

    name: Ubuntu-${{ matrix.BUILD_TYPE }}-${{matrix.COMPILER}}
    runs-on: ${{ matrix.os }}

    # Set up a global environment variable for build scripts
    env:
      SIMDB_BUILD_TYPE: ${{ matrix.BUILD_TYPE }}
      COMPILER:         ${{ matrix.COMPILER }}

    steps:
      - name: Setup Git Identity
        run: |
          git config --global user.email "runner@github.com"
          git config --global user.name "Github Runner"

      # Get SimDB
      - name: Clone SimDB
        uses: actions/checkout@v4

      # Install missing packages to make everything build
      - name: Install packages needed for SimDB
        run: |
          sudo apt-get update --fix-missing
          sudo apt-get install libboost-all-dev llvm lld sqlite3 libsqlite3-dev

      # Invoke CMake
      - name: CMake
        run: ./.github/actions/cmake.sh

      # Regress
      - name: Regress
        run: ./.github/actions/regress.sh

      # Save error logs, etc
      - name: Save artifacts
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ErrorLogs-${{matrix.BUILD_TYPE}}-${{matrix.COMPILER}}
          path: ${{matrix.BUILD_TYPE}}/
